services:
  mongodb:
    image: mongo
    container_name: mongo-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - microservices
  users:
    build: 
      context: ./User
      target: dev
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://admin:admin@mongodb:27017/moviesdb?authSource=admin
      - PORT=3000
    container_name: user_manager
    ports:
      - "3000:3000"
    networks:
      - microservices
    volumes:
      - ./User:/usr/src/app
      - /usr/src/app/node_modules

  auth:
    build:
      context: ./Authentication
      target: dev
      dockerfile: Dockerfile
    environment:
      - DEBUG=auth:*
      - MONGO_URL=mongodb://admin:admin@mongodb:27017/moviesdb?authSource=admin
      - PORT=3001
      - SECRET_JWT_KEY=CodigoEspagueti
      - USER_MANAGER_ENDPOINT=http://users:3000
    container_name: authentication
    ports: 
      - "3001:3001"
    networks:
      - microservices
    volumes:
      - ./Authentication:/usr/src/app
      - /usr/src/app/node_modules
  api-gateway:
    build:
      context: ./ApiGateway
      target: dev
      dockerfile: Dockerfile
    environment:
      - DEBUG=api-gateway:*
      - PORT=3002
      - SECRET_JWT_KEY=CodigoEspagueti
      - AUTH_ENDPOINT=http://auth:3001/
      - USER_MANAGE_ENDPOINT=http://users:3000/
      - RANKING_ENDPOINT=http://calificacion:4000/
      - OPINIONS_ENDPOINT=http://opiniones:4100/
    container_name: api-gateway
    ports: 
      - "3002:3002"
    networks:
      - microservices
    volumes:
      - ./ApiGateway:/usr/src/app
      - /usr/src/app/node_modules
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - microservices

  calificacion:
    build: ./Ranking
    container_name: calificacion
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://admin:admin@mongodb:27017/calificacion_db?authSource=admin
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_EXCHANGE=ratings
      - RABBITMQ_EXCHANGE_TYPE=topic
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - microservices

  opiniones:
    build: ./Opinions
    container_name: opiniones
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - PORT=4100
      - MONGO_URL=mongodb://admin:admin@mongodb:27017/calificacion_db?authSource=admin
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_EXCHANGE=ratings
      - QUEUE_NAME=opinions_queue
    ports:
      - "4100:4100"
    restart: unless-stopped
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  rabbitmq_data:
    driver: local