services:
  mongodb:
    image: mongo
    container_name: mongo-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - microservices
  users:
    build: 
      context: ./user
      target: dev
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://admin:admin@mongodb:27017/moviesdb?authSource=admin
      - PORT=3000
    container_name: user_manager
    ports:
      - "3000:3000"
    networks:
      - microservices
    volumes:
      - ./User:/usr/src/app

networks:
  microservices:
    driver: bridge

volumes:
  mongo-data:
    driver: local